name: Build Unity Project & Deploy to S3

on: 
  pull_request:
    branches:
      - 'release'
    types:
      - closed
    
env:
  PR_LABEL: ${{ github.event.pull_request.labels[0].name }}
  PATCHER_PATH: PatcherWorkspace
  UNITY_BUILD_PATH: ./PatcherWorkspace/App
  UNITY_PROJECT_PATH: DeploymentTest
  UNITY_LIBRARY-PATH: DeploymentTest/Library
  BUILDS_PATH: PatcherWorkspace/Builds
  PATCHES_PATH: PatcherWorkspace/Patches
  AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  unityBuild:
    if: github.event.pull_request.merged # Don't run if PR wasn't merged.
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
    steps:
      - name: Check PR label. # Don't run if PR doesn't have valid labels.
        if: ${{ !contains(fromJson('["major", "minor", "patch"]'), env.PR_LABEL) }}
        run: |
         echo Invalid label: "${{ env.PR_LABEL }}". Must be either "major", "minor", or "patch"
         exit 1

      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - uses: actions/cache@v3 # Cache Library directories to optimize workflow duration.
        with:
          path: ${{ env.UNITY_LIBRARY-PATH }}
          key: ${{ env.UNITY_LIBRARY-PATH }}-${{ matrix.targetPlatform }}
          restore-keys: ${{ env.UNITY_LIBRARY-PATH }}-
      
      - uses: game-ci/unity-builder@v2 # Build the game in $PATCHER_PATH/App directory.
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: ${{ env.UNITY_PROJECT_PATH }}
          buildsPath: ${{ env.UNITY_BUILD_PATH }}
      
      - name: Copy Builds from S3
        run: >
          aws s3 cp s3://${{ env.AWS_S3_BUCKET }}/Testing/${{ matrix.targetPlatform }}/Builds/ ${{ env.BUILDS_PATH }} --recursive
          
      - name: Copy Patches from S3
        run: >
          aws s3 cp s3://${{ env.AWS_S3_BUCKET }}/Testing/${{ matrix.targetPlatform }}/Patches/ ${{ env.PATCHES_PATH }} --recursive
      
      - name: Grant patcher permissions.  # Elevate patcher's permissions for write/read purposes.
        working-directory: ${{ env.PATCHER_PATH }}
        run: sudo chmod 777 ./MHLab.Patch.Admin
      
      - name: Run patcher build command. # Generate a build with patcher using PR label as a version flag i.e major, minor, or patch.
        working-directory: ${{ env.PATCHER_PATH }}
        run: ./MHLab.Patch.Admin build -r ${{ env.PR_LABEL }}
      
      - name: Run patcher patch command. # Generate a patch between the two latest builds.
        working-directory: ${{ env.PATCHER_PATH }}
        run: ./MHLab.Patch.Admin patch -c 9
        
      - name: Run patcher cleanUp command. # This is a custom command that deletes redundant builds and patches, and updates the indices.
        id: clean-up
        working-directory: ${{ env.PATCHER_PATH }}
        run: ./MHLab.Patch.Admin cleanUp
        
      - name: Create version tag. # Create a version tag with the v prefix and target platform e.g. v1.2.0-StandaloneOSX
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.clean-up.outputs.LATEST_BUILD }}-${{ matrix.targetPlatform }}

      - name: Sync Builds to S3
        run: >
          aws s3 sync ${{ env.BUILDS_PATH }} s3://${{ env.AWS_S3_BUCKET }}/Testing/${{ matrix.targetPlatform }}/Builds/ --delete
          
      - name: Sync Patches to S3
        run: >
          aws s3 sync ${{ env.PATCHES_PATH }} s3://${{ env.AWS_S3_BUCKET }}/Testing/${{ matrix.targetPlatform }}/Patches/ --delete
        
      

